### ISSUE TITLE
iOS 6 Safari: cover content not shown in the middle of the screen

### ISSUE THREAD

**Issue by ronxjansen** [flipbase/www#10]
<img width="1440" alt="screen shot 2017-06-14 at 13 03 22" src="https://user-images.githubusercontent.com/461952/27130044-da59f204-5104-11e7-86a9-524686490978.png">

**Comment by ronxjansen** [comment]
Some issue appears on Galaxy S5 Chrome:

<img width="1440" alt="screen shot 2017-06-14 at 13 35 58" src="https://user-images.githubusercontent.com/461952/27130378-74d9c088-5106-11e7-9cc5-f63d272506ff.png">

**Comment by SZharkov** [comment]
Fixed
