### ISSUE TITLE
Cannot click on the 'products' item in the navigation on iPhone 5s

### ISSUE THREAD

**Issue by ronxjansen** [flipbase/www#2]
You cant click on the top item 'products' because the flipbase.com logo  appears to be in front of it. 

<img width="1440" alt="screen shot 2017-06-14 at 13 07 03" src="https://user-images.githubusercontent.com/461952/27129458-a9b2bd36-5102-11e7-92b0-82c58fdced8d.png">

**Comment by ronxjansen** [comment]
This happens on the iPhone 5:

<img width="1440" alt="screen shot 2017-06-14 at 13 57 26" src="https://user-images.githubusercontent.com/461952/27131091-7849c58a-5109-11e7-9179-30e8305a4162.png">

**Comment by SZharkov** [comment]
![image](https://user-images.githubusercontent.com/13063421/27257263-6e478744-53d8-11e7-8b5a-56f37a1aee98.png)

Fixed

**Comment by ronxjansen** [comment]
I'm not sure this issue is fixed; I have tested this issue on 3 iOS devices and they all show the same issue:

<img width="1440" alt="screen shot 2017-06-21 at 10 48 50" src="https://user-images.githubusercontent.com/461952/27375369-3c7cf994-566f-11e7-8dfc-e216dc950700.png">
<img width="1440" alt="screen shot 2017-06-21 at 10 43 34" src="https://user-images.githubusercontent.com/461952/27375373-3ed040de-566f-11e7-9140-9c528f08f003.png">

**Comment by SZharkov** [comment]
Check the new commit
