### ISSUE TITLE
On IE9 bxslider on sollicitatie-proces page is not working/loaded properly

### ISSUE THREAD

**Issue by ronxjansen** [flipbase/www#3]
<img width="1440" alt="screen shot 2017-06-14 at 13 01 28" src="https://user-images.githubusercontent.com/461952/27129484-cf176cf2-5102-11e7-9576-a5f625cc0318.png">

**Comment by SZharkov** [comment]
fixed
![image](https://user-images.githubusercontent.com/13063421/27253220-18e06cda-5379-11e7-8445-e0c5359b46b7.png)
