### ISSUE TITLE
On IE9 no content is visible on employer-branding, sollicitatie-proces and jobs pages

### ISSUE THREAD

**Issue by ronxjansen** [flipbase/www#4]
<img width="1440" alt="screen shot 2017-06-14 at 12 43 53" src="https://user-images.githubusercontent.com/461952/27129513-f8d50356-5102-11e7-8345-99e0231145d9.png">

**Comment by SZharkov** [comment]
![image](https://user-images.githubusercontent.com/13063421/27257255-21cd502e-53d8-11e7-8383-f7e0527ce9e9.png)
Fixed
