### ISSUE TITLE
IE9: the 'white' navigation is shown instead of the 'dark' theme on the /blog and privacy-policy pages

### ISSUE THREAD

**Issue by ronxjansen** [flipbase/www#9]
<img width="1440" alt="screen shot 2017-06-14 at 13 19 01" src="https://user-images.githubusercontent.com/461952/27129848-121ece0e-5104-11e7-8cbc-392e5e35508f.png">

**Comment by ronxjansen** [comment]
On IE10 this appears to be okay: 

<img width="1440" alt="screen shot 2017-06-14 at 13 21 14" src="https://user-images.githubusercontent.com/461952/27129927-5bbf3058-5104-11e7-9b53-33e526f839c2.png">

**Comment by SZharkov** [comment]
Fixed
